import test from 'node:test';
import assert from 'node:assert/strict';
import {createService} from './sauna-service.mjs';
function setup(){const tables=new Map();let n=0;const table=k=>{if(!tables.has(k))tables.set(k,new Map());return tables.get(k);};const db={async list(k){return {items:[...table(k)].map(([id,v])=>({id,...structuredClone(v)}))};},async add(k,items){return items.map(r=>{const id=String(++n);table(k).set(id,structuredClone(r));return id;});},async get(k,ids){return ids.map(id=>structuredClone(table(k).get(id)||null));},async update(k,items){return items.map(({id,record})=>{table(k).set(id,record);return true;});}};return {tables,db,run:createService({db,ai:{generate:async()=>({text:'Prueba'})},parsePdf:async()=>({text:'Prueba'})})};}
const worker={uid:'staff',role:'trabajador',name:'Persona QA',panelPersonal:true},admin={uid:'admin',role:'admin',name:'Admin QA'},other={uid:'other',role:'trabajador',name:'Otra persona'},date='2026-09-07';
const report={date,category:'extra',title:'Orden adicional',description:'Ordené las piezas después de mi actividad.',minutes:20,performed:true,operationId:'op-1'};
test('recipient can report extra work but cannot create tasks meals purchases or events',async()=>{const {run,tables}=setup();for(const kind of ['task','meal','shopping','event'])await assert.rejects(run('personal-create',{date,kind,title:'Me asigno',operationId:kind},worker),e=>e.status===403);const a=await run('extra-create',report,worker);assert.equal(a.assignedTaskCreated,false);assert.equal((await run('extra-list',{date},worker)).items.length,1);assert.ok([...tables.keys()].every(k=>!['actividades','asistencias','proyectos','compras'].includes(k)));});
test('only owner or administration sees extra work; staff cannot spoof completion review',async()=>{const {run}=setup();const a=await run('extra-create',report,worker);await assert.rejects(run('extra-list',{date,userId:'staff'},other),e=>e.status===403);await assert.rejects(run('extra-review',{date,id:a.id,accepted:true,comment:'Yo apruebo',operationId:'r'},worker),e=>e.status===403);const inbox=await run('extra-inbox',{date,userIds:['staff']},admin);assert.equal(inbox.items[0].title,report.title);await run('extra-review',{date,userId:'staff',id:a.id,accepted:true,comment:'Revisado con la persona.',operationId:'review'},admin);const state=await run('extra-list',{date},worker);assert.equal(state.items[0].status,'revisado');assert.equal(state.items[0].reviewer,admin.name);});
test('shortages remain requests rather than assigned purchases and retries keep a single report',async()=>{const {run}=setup();const r={...report,category:'faltante'};const one=await run('extra-create',r,worker),two=await run('extra-create',r,worker);assert.equal(one.id,two.id);const items=(await run('extra-list',{date},worker)).items;assert.equal(items.length,1);assert.equal(items[0].status,'pendiente_revision');await assert.rejects(run('extra-create',{...r,performed:false},worker),e=>e.status===400);await assert.rejects(run('extra-create',{...r,date:'2099-01-01'},worker),e=>e.status===400);});
test('new user policy preserves admin plans and worker checkmarks, denies edits even to legacy own plans',async()=>{const {run}=setup();const p=await run('personal-create',{date,userId:'staff',kind:'shopping',title:'Comprar productos',operationId:'p'},admin);await run('personal-change',{date,id:p.id,change:'complete',done:true,operationId:'done'},worker);assert.equal((await run('personal-list',{date},worker)).items[0].done,true);await assert.rejects(run('personal-change',{date,id:p.id,change:'edit',title:'Cambiar lista',operationId:'edit'},worker),e=>e.status===403);});
test('engineering authorization cannot be forged and measures have immutable followup',async()=>{const {run}=setup();await assert.rejects(run('engineering-list',{date,panelIngenieria:true},worker),e=>e.status===403);const engineer={...worker,panelIngenieria:true};const r=await run('engineering-create',{date,category:'calidad',title:'Revisión QA',planned:4,actual:3,rejected:1,operationId:'m'},engineer);await run('engineering-update',{date,id:r.id,status:'cerrado',comment:'Medición revisada.',operationId:'close'},admin);const list=(await run('engineering-list',{date},engineer)).items;assert.equal(list[0].status,'cerrado');assert.equal(list[0].history[0].actorName,admin.name);});
test('training inbox is private and pagination bounds are enforced',async()=>{const {run}=setup();await run('training-request',{language:'en',operationId:'learn'},worker);await assert.rejects(run('training-inbox',{userIds:['staff']},other),e=>e.status===403);assert.equal((await run('training-inbox',{userIds:['staff']},admin)).items[0].language,'en');await assert.rejects(run('training-inbox',{userIds:Array(9).fill('staff')},admin),e=>e.status===400);});
