// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvb1kOvxvPTZzCZLQx6aZgEBnC-AZnYE',
    appId: '1:1083212885362:web:0b99846f25c4d5c005c1eb',
    messagingSenderId: '1083212885362',
    projectId: 'saunastiloapp-17e15',
    authDomain: 'saunastiloapp-17e15.firebaseapp.com',
    storageBucket: 'saunastiloapp-17e15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3hpOQEUU4qfgRPbkzZQE3hKgY-PTr_4Q',
    appId: '1:1083212885362:android:5dbc7c758d23f96105c1eb',
    messagingSenderId: '1083212885362',
    projectId: 'saunastiloapp-17e15',
    storageBucket: 'saunastiloapp-17e15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqLB6_nsUfqcc6Ya0DT6Ve927P_jIpEIg',
    appId: '1:905977113744:ios:64e6ef86a878c028f27c15',
    messagingSenderId: '905977113744',
    projectId: 'saunastylo-dbd87',
    storageBucket: 'saunastylo-dbd87.firebasestorage.app',
    iosBundleId: 'com.saunastylo.saunastylo',
  );
}
